### ISSUE TITLE
Erro de Build Devido a Compilador(es) Desconhecido(s) no Dockerfile

### ISSUE THREAD

**Issue by flustosa** [ricardonascimentosoares/cadastro-materiais-gov#1]
#### Descrição

Ao rodar o build com o Dockerfile, encontrei o seguinte erro:

```
Project name: NumPy
Project version: 1.26.3
ERROR: Unknown compiler(s): [['cc'], ['gcc'], ['clang'], ['nvc'], ['pgcc'], ['icc'], ['icx']]
```

#### Análise

O problema ocorre porque o Dockerfile atualmente usa a tag `python:3-slim`, que baixa a versão mais recente do Python. A versão mais recente é incompatível com as dependências especificadas no arquivo `requirements.txt`, particularmente com a indicada para o Numpy (1.26.3).

#### Solução Proposta

Indicar uma versão específica para o Python no Dockerfile que seja compatível com as dependências. Testei com `python:3.10.15-slim`, e o processo de build foi concluído com sucesso.

**Obs.**: Apesar do código funcionar, não é possível utilizar a aplicação pois os endpoints do compras.dados.gov.br estão indisponíveis (503).

**Comment by ricardonascimentosoares** [comment]
Olá Felipe! Muito obrigado, pelo feedback e solução proposta!

Sobre os endpoints, precisaria dar uma analisada pra ver se continuam os mesmos, pois podem ter sido alterados (não tenho trabalhado nesse projeto há algum tempo...).
Mas, de fato, a versão da imagem deveria ter sido especificada no Dockerfile. Poderia, por favor, abrir um PR com a sua solução?

Desde já, agradeço!!
